/**
 * ObiTracker entity types and insert DTOs.
 *
 * These interfaces mirror the Supabase public schema exactly.
 * Column order matches the schema definition — do not reorder.
 * If the schema changes, update these types alongside the migration.
 */

export interface Dog {
  id: string;
  account_id: string;
  name: string;
  created_at: string;
  updated_at: string;
}

export interface TrainingElement {
  id: string;
  dog_id: string;
  name: string;
  sort_position: number;
  created_at: string;
}

export interface TrainingLog {
  id: string;
  element_id: string;
  dog_id: string;
  account_id: string;
  /** ISO date string ("YYYY-MM-DD"). Records the day of the training cell, not the time of entry (FR-006). */
  trained_on: string;
}

// ---------------------------------------------------------------------------
// Insert DTOs — fields required on INSERT (generated columns omitted)
// ---------------------------------------------------------------------------

/** Insert payload for dogs. `id`, `created_at`, and `updated_at` are generated by the database. */
export type NewDog = Pick<Dog, "name">;

/** Insert payload for training_elements. `id` and `created_at` are generated by the database. */
export type NewTrainingElement = Pick<TrainingElement, "dog_id" | "name" | "sort_position">;

/** Insert payload for training_logs. `id` is generated by the database; no `created_at` on this table. */
export type NewTrainingLog = Pick<TrainingLog, "element_id" | "dog_id" | "account_id" | "trained_on">;
