/**
 * ObiTracker entity types and insert DTOs.
 *
 * These interfaces mirror the Supabase public schema exactly.
 * Column order matches the schema definition — do not reorder.
 * If the schema changes, update these types alongside the migration.
 */

export interface Dog {
  id: string;
  account_id: string;
  name: string;
  created_at: string;
  updated_at: string;
  is_deleted: boolean;
  deleted_at: string | null;
}

export interface TrainingElement {
  id: string;
  dog_id: string;
  name: string;
  sort_position: number;
  created_at: string;
}

export interface TrainingLog {
  id: string;
  element_id: string;
  dog_id: string;
  account_id: string;
  /** ISO date string ("YYYY-MM-DD"). Records the day of the training cell, not the time of entry (FR-006). */
  trained_on: string;
}

export interface CompetitionClass {
  id: string;
  name: string;
  sort_position: number;
  created_at: string;
  class_number: number;
}

export interface Exercise {
  id: string;
  class_id: string;
  name: string;
  shortcut: string;
  multiplier: number;
  sort_position: number;
  created_at: string;
}

export interface Competition {
  id: string;
  dog_id: string;
  class_id: string;
  account_id: string;
  /** ISO date string ("YYYY-MM-DD"). The date the competition was held. */
  competed_on: string;
  created_at: string;
}

export interface CompetitionScore {
  id: string;
  competition_id: string;
  exercise_id: string;
  account_id: string;
  /** Raw (unmultiplied) points, 0–10 in quarter-point increments. */
  score: number;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Insert DTOs — fields required on INSERT (generated columns omitted)
// ---------------------------------------------------------------------------

/**
 * Insert payload for dogs. `id`, `created_at`, and `updated_at` are generated by the database.
 *
 * `account_id` is intentionally absent: it is injected from the authenticated session in the
 * service layer and must never come from user input.
 * `is_deleted` and `deleted_at` are database-defaulted (FALSE / NULL) and omitted from inserts.
 */
export type NewDog = Pick<Dog, "name">;

/** Insert payload for training_elements. `id` and `created_at` are generated by the database. */
export type NewTrainingElement = Pick<TrainingElement, "dog_id" | "name" | "sort_position">;

/** Insert payload for training_logs. `id` is generated by the database; no `created_at` on this table. */
export type NewTrainingLog = Pick<TrainingLog, "element_id" | "dog_id" | "account_id" | "trained_on">;

/**
 * Insert payload for competitions. `id` and `created_at` are generated by the database.
 * `account_id` is intentionally absent: it is injected from the authenticated session in the
 * service layer and must never come from user input.
 */
export type NewCompetition = Pick<Competition, "dog_id" | "class_id" | "competed_on">;

/**
 * Insert payload for competition_scores. `id`, `created_at`, and `updated_at` are generated by
 * the database. `account_id` is intentionally absent: it is injected from the authenticated
 * session in the service layer and must never come from user input.
 */
export type NewCompetitionScore = Pick<CompetitionScore, "competition_id" | "exercise_id" | "score">;
